services:
  - type: web
    name: land-document-backend
    env: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_URL
        value: postgresql://land_document_db_user:uy2rp95mZF7vpPJOy2LKXcILnlZ2fGdc@dpg-da989sks728c73d1ejj0-a/land_document_db
      - key: NEO4J_URI
        value: bolt://localhost:7687
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        value: password

  - type: web
    name: land-document-frontend
    env: docker
    region: oregon
    plan: free
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: REACT_APP_API_URL
        value: https://land-document-backend.onrender.com
